### ISSUE TITLE
Consider migrating to scraping Google News RSS feed

### ISSUE THREAD

**Issue by omgimanerd** [omgimanerd/getnews.tech#11]
The [Google News RSS feed](https://news.google.com/rss/search?q=bitcoin&hl=en-US&gl=US&ceid=US:en) has similar functionality and scraping this would have no rate limit.

Pros:
  - No rate limit
  - Equally advanced querying functionality

Cons:
  - Undocumented API / query parameters
  - Article descriptions are sparse

**Comment by chubin** [comment]
@omgimanerd If you use aggressive caching (what I recommend), the rate limit will be hopefully not a big problem. But if it is still a problem even with caching, you may consider using Google News RSS as a fall back.

Also, consider creating some sort of modular architecture, so getnews can be used as a terminal adapter to various news sites including reddit and slashdot

**Comment by omgimanerd** [comment]
The NewsAPI itself does a lot of caching already, but I'm limited to 500 requests/day. It's hard to cache results because different people will query a lot of different things, and caching based on query probably won't help that.

Since I want reasonable result freshness, the cache expiration would be at most 5 minutes, which doesn't seem to offer me that much. As of now, I'm not too worried about the rate limit yet, but using Google News RSS as a fallback sounds like a good idea. This application was designed to fill a niche as a news-in-terminal application, and there are plenty of RSS reader applications out there.

**Comment by omgimanerd** [comment]
Working on this in #18
