### ISSUE TITLE
Server down ? 

### ISSUE THREAD

**Issue by martinsauve** [omgimanerd/getnews.tech#12]
{20-03-17 7:13}manjaro:~ martin% curl getnews.tech 
┌──────────────────────────────────────────────────────────────────────────────┐ 
│                                                                              │ 
│            An error occurred on our end. Please try again later.             │ 
│                                                                              │ 
│                           curl getnews.tech/:help                            │ 
│                                                                              │ 
├──────────────────────────────────────────────────────────────────────────────┤ 
│                Powered by the News API (https://newsapi.org).                │ 
│                  Follow @omgimanerd on Twitter and GitHub.                   │ 
│                    Open source contributions are welcome!                    │ 
│                  https://github.com/omgimanerd/getnews.tech                  │ 
└──────────────────────────────────────────────────────────────────────────────┘

**Comment by omgimanerd** [comment]
Thanks for reporting this! The mongo instance in prod crashed, which caused the url shortener to fail.

**Comment by omgimanerd** [comment]
Fixed, although I need to consider making this restart automated.
