### ISSUE TITLE
get news.tech seems down

### ISSUE THREAD

**Issue by gbstan** [omgimanerd/getnews.tech#13]
It seems that the website is down.

curl getnews.tech/ doesn't return anything.

**Comment by omgimanerd** [comment]
Restarted, thanks for the heads up. It seems like mongodb crashing is becoming a rather persistent problem.

**Comment by omgimanerd** [comment]
I added a cronjob to the prod server that restarts mongodb every day at 0300. Perhaps this will reduce the frequency of these crashes, although I should probably set up some form of monitoring as well.
