### ISSUE TITLE
curl getnews.tech not working anymore

### ISSUE THREAD

**Issue by gbstan** [omgimanerd/getnews.tech#24]
It seems that this is not working anymore:

`curl getnews.tech/anything` returns the following:

```html
<html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>
```

**Comment by omgimanerd** [comment]
Sorry, fixed. I have not had time to look at a lot of my projects recently. This was due to DigitalOcean restarting the droplet. I will set up pm2 to auto restart the process over the next week.

**Comment by gbstan** [comment]
It seems this is not working any more for some reason. Same issue as above is happening for the moment.

**Comment by omgimanerd** [comment]
Thanks for letting me know, there was a brief digitalocean outage which affected my droplet. I've restarted the instance.
